export const campaigns = [
  {
    id: "ramadan-feast", 
    title: "Ramadan Feast",
    description: "Relive the warmth of togetherness. A look back at our curated culinary journey of authentic Indonesian flavors.",
    image: "/images/webp/RF1.webp", 
    ctaText: "View Archive",
    ctaLink: "/experiences/ramadan-feast", 
    isActive: false, 
  },
  {
    id: "weekday-specials", 
    title: "Weekday Specials",
    description: "Elevate your mid-week dining. Enjoy exclusive privileges and curated tasting menus from Monday to Thursday.",
    image: "/promo/WS-1.webp", 
    ctaText: "Discover More",
    ctaLink: "/experiences/weekday-specials", 
    isActive: false, 
  }, 
  {
    id: "may-madness", 
    title: "May Madness",
    description: "A lunch experience, redefined. Freshly prepared by order, thoughtfully served to your table.",
    image: "/images/webp/MM-FULL.webp", 
    ctaText: "Discover More",
    ctaLink: "/experiences/may-madness", 
    isActive: false, 
  },
  {
    id: "june-table", 
    title: "June Table",
    description: "Discover our exclusive lifestyle lunch set. A 4-course culinary journey designed for the perfect midday escape.",
    image: "/images/june/junetable.webp", 
    ctaText: "Discover More",
    ctaLink: "/experiences/june-table", 
    isActive: false, 
  },
   {
    id: "house-music", 
    title: "",
    description: "",
    image: "/campaigns/house-music.jpg", 
    ctaText: "Discover More",
    ctaLink: "/experiences/house-music", 
    isActive: true, 
  },
];